theme: jekyll-theme-slate

# Permalink format for blog posts
# this matches what Wordpress does, to prevent link rot
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-paginate-v2

# Controls how many posts show up on the blog page
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/:num/'
  sort_field: 'date'
  sort_reverse: true
  title: ':title'
